A = [ 'A', 'AN', "THE", "THIS", "THAT", "THOSE", "WE", "OUR", "THEIR", "HUNDREDS OF", "THOUSANDS OF", ]
B = [ "BALL", "BAT", "FOO", "BAR", "LEFT", "RIGHT", "UP", "DOWN", "SIDEWAYS",
      "CORRIDOR", "DOOR", "TREE", "HAT", "DIAMOND", "SHOVEL", "PAINTING",
      "COMPOSED OF", "HEINOUS", "",]
C = [ "RIBBON", "GELATIN", "POLITICIAN", "SOURCE CODE", "MONITOR", "BOSS",
      "GRAVE", "HORSE", "PHANTASM", "MALE", "FEMALE", "CHILD", "GOAT", "FROG",
      "FERRET", "INSURRECTION", "DAWN", "",]
D = [ "ATE", "KILLED", "MANGLED", "DISEASED", "FORGOT", "REMEMBERED", "DESTROYED",
      "DISASSEMBLED", "RESURRECTED", "FELLATED", "EMBRACED", "NUMBED", "WISHED",
      "WHISKED", "ENRAGED", "SUPPLANTED", "OVERTHREW",]
E = [ "NEW YORK", "CALIFORNIA", "SYMPHONIA", "ISIS", "CRYSTALIS", "IDAHO", "WHOREHOUSES",
      "CELLULAR PROVIDERS", "GERIATRIC PATIENTS", "CORPOREAL BEINGS", "DEITIES", "SLUTS",
      "FOREIGNERS", ""]
F = [ "QUICKLY", "QUIETLY", "", "SLOWLY", "LOUDLY", "HEAVILY", "DELICATELY", "MORBIDLY",
      "UNASSUMEDLY", "CONFIDENTLY", "WITH REGRET", "HAUNTINGLY", "PAINFULLY", "JOYOUSLY",
      "INSIPIDLY"]
